nginx:
	container_name: nginx
  	restart: always
  	build: ./nginx
  	ports:
    	- "80:80"
  	volumes_from:
    	- django
  	links:
    	- django:django

django:
   	container_name: django
   	restart: always
   	build: ./django
   	expose:
     	- "8000"
	volumes:
    	- ./django:/usr/src/app
    links:
        - postgres:postgres
	command: /usr/local/bin/gunicorn project.wsgi:application -w 2 -b :8000

postgres:
	container_name: postgres
  	restart: always
   	image: postgres
   	expose:
     	- "5432"
   	environment:
     	- POSTGRES_DB=postgres
     	- POSTGRES_USER=postgres
     	- POSTGRES_PASSWORD=postgres
   	volumes:
     	- ./postgres:/var/lib/postgresql/data
