owncloud:
  image: owncloud:latest
  restart: always
  ports:
    - "80:80"
  volumes:
    - ./owncloud/apps:/var/www/html/apps
    - ./owncloud/data:/var/www/html/data
    - ./owncloud/config:/var/www/html/config
  links:
    - postgres
    - redis

postgres:
   restart: always
   image: postgres
   expose:
     - "5432"
   environment:
     - POSTGRES_DB=owncloud
     - POSTGRES_USER=owncloud
     - POSTGRES_PASSWORD=owncloud
   volumes:
     - ./postgres:/var/lib/postgresql/data

redis:
  image: redis:latest
  restart: always
  expose:
    - "6379"
