web:
  container_name: web
  restart: always
  build: ./web
  expose:
    - "8000"
  volumes:
    - ./web:/usr/src/app
  command: /usr/local/bin/gunicorn project.wsgi:application -w 2 -b :8000

nginx:
  container_name: nginx
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web
